spring:
  datasource:
    url: jdbc:mariadb://i9e101.p.ssafy.io:3306/mlm
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
  redis:
    host: i9e101.p.ssafy.io
    port: 6379
  servlet:
    multipart:
      location: c:\\upload
      maxFileSize: 200MB
      maxRequestSize: 100MB

jpa:
  generate-ddl: true
  show-sql: true

google:
  client-id: ${CLINETID}
  client-secret: ${CLIENTSECRET}
  redirect-uri: http://i9e101.p.ssafy.io:8080/oauth/google/callback

iot:
  N: ${N}
  RSA: ${RSA}
  RSB: ${RSB}

server:
  address: 0.0.0.0
  port: 8090

data:
  service-key: ${SERVICE_KEY}

chatgpt:
  api-key: ${CHATGPT_API_KEY}
