spring:
  datasource:
    url: jdbc:mariadb://i9e101.p.ssafy.io:3306/mlm
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mlmMDB6
  redis:
    host: i9e101.p.ssafy.io
    port: 6379
  servlet:
    multipart:
      location: c:\\upload
      maxFileSize: 200MB
      maxRequestSize: 100MB

jpa:
  generate-ddl: true
  show-sql: true

google:
  client-id:  627028807402-fobgohrdmv1ov823iiij7omtp89p2onb.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8080/oauth/token

iot:
  N: 1517
  RSA: 1421
  RSB: 1061

server:
  address: 0.0.0.0
  port: 8080

data:
  service-key: '%2FoTPUAndmigHQ%2BpPwXOuYoVbqfXclp89LQ0mnAeXcFidTxdpxB9h9c2qIbJGNqkIFfkQgFeWqU4cLC3%2FHu%2BkMQ%3D%3D'

chatgpt:
  api-key: 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